dsn:
  database: transfer_system
  user: postgres
  password: postgres
  host: postgres
  port: 5432
  # minsize: 1
  # maxsize: 50

init:
  database: postgres
  user: postgres
  password: postgres
  host: postgres
  port: 5432
  # minsize: 1
  # maxsize: 50
